# Generated by Django 3.2.6 on 2021-10-04 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0006_alter_assignment_status'),
        ('rider_app', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub_app.hub')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rider_app.rider')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='bucket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rider_app.bucket'),
        ),
    ]
