# Generated by Django 3.2.6 on 2021-10-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0003_auto_20211004_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('initiated', 'initiated'), ('completed', 'completed')], default='initiated', max_length=32),
        ),
    ]
