# Generated by Django 3.2.6 on 2021-10-04 07:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='bucket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='rider_app.bucket'),
        ),
    ]
