# Generated by Django 3.2.6 on 2021-10-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0006_auto_20211004_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bucket',
            field=models.ManyToManyField(related_name='tasks', to='rider_app.Bucket'),
        ),
    ]
