# Generated by Django 3.2.6 on 2021-10-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0008_auto_20211004_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='distance',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('initiated', 'initiated'), ('assigned', 'assigned'), ('completed', 'completed')], default='initiated', max_length=32),
        ),
    ]
