# Generated by Django 3.2.6 on 2021-10-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0009_auto_20211004_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='photo',
            field=models.ImageField(null=True, upload_to='rider-profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('initiated', 'initiated'), ('assigned', 'assigned'), ('completed', 'completed'), ('tried', 'tried')], default='initiated', max_length=32),
        ),
    ]
