# Generated by Django 3.2.6 on 2021-10-08 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub_app', '0014_alter_assignment_status'),
        ('rider_app', '0010_auto_20211007_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RiderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub_app.hub')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_app.rider')),
            ],
        ),
    ]
