# Generated by Django 3.2.6 on 2021-10-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0013_alter_rider_id_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='id_proof',
            field=models.ImageField(null=True, upload_to='id_proof', verbose_name='id_proof'),
        ),
    ]
