# Generated by Django 3.2.6 on 2021-10-11 08:52

from django.db import migrations, models
import rider_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0014_alter_rider_id_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='id_proof',
            field=models.ImageField(null=True, upload_to=rider_app.models.get_upload_path, verbose_name='id_proof'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='photo',
            field=models.ImageField(null=True, upload_to=rider_app.models.get_upload_path),
        ),
    ]
