# Generated by Django 3.2.6 on 2021-09-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
