# Generated by Django 3.2.6 on 2021-09-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='transit_type',
            field=models.CharField(choices=[('forward', 'forward'), ('return', 'return')], default='forward', max_length=40),
        ),
    ]
