# Generated by Django 3.2.6 on 2021-09-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0003_auto_20210929_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(default='collect', max_length=128),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('collected', 'collected'), ('initiated', 'initiated'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='initiated', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='transit_type',
            field=models.CharField(choices=[('forward', 'forward'), ('return', 'return')], default='forward', max_length=40),
        ),
    ]
