# Generated by Django 3.2.6 on 2021-10-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0004_auto_20210929_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('cancelled', 'cancelled'), ('collected', 'collected'), ('delivered', 'delivered'), ('initiated', 'initiated')], default='initiated', max_length=200),
        ),
    ]
