# Generated by Django 3.2.6 on 2021-10-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0008_auto_20211004_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('initiated', 'initiated'), ('cancelled', 'cancelled'), ('collected', 'collected')], default='initiated', max_length=200),
        ),
    ]
