# Generated by Django 3.2.6 on 2021-10-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0011_auto_20211004_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('collected', 'collected'), ('initiated', 'initiated'), ('assigned', 'assigned'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='initiated', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='transit_type',
            field=models.CharField(choices=[('return', 'return'), ('forward', 'forward')], default='forward', max_length=40),
        ),
    ]
