# Generated by Django 3.2.6 on 2021-10-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0013_auto_20211007_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('initiated', 'initiated'), ('cancelled', 'cancelled'), ('delivered', 'delivered'), ('collected', 'collected'), ('assigned', 'assigned')], default='initiated', max_length=200),
        ),
    ]
