# Generated by Django 3.2.6 on 2021-10-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0016_auto_20211011_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'assigned'), ('delivered', 'delivered'), ('collected', 'collected'), ('cancelled', 'cancelled'), ('initiated', 'initiated')], default='initiated', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='transit_type',
            field=models.CharField(choices=[('return', 'return'), ('forward', 'forward')], default='forward', max_length=40),
        ),
    ]
