# Generated by Django 3.2.6 on 2021-10-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0017_auto_20211011_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'assigned'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('initiated', 'initiated'), ('collected', 'collected')], default='initiated', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='transit_type',
            field=models.CharField(choices=[('forward', 'forward'), ('return', 'return')], default='forward', max_length=40),
        ),
    ]
