# Generated by Django 3.2.6 on 2021-10-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0018_auto_20211011_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('collected', 'collected'), ('assigned', 'assigned'), ('initiated', 'initiated'), ('cancelled', 'cancelled'), ('delivered', 'delivered')], default='initiated', max_length=200),
        ),
    ]
