# Generated by Django 3.2.6 on 2021-10-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0019_alter_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('initiated', 'initiated'), ('cancelled', 'cancelled'), ('delivered', 'delivered'), ('assigned', 'assigned'), ('collected', 'collected')], default='initiated', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='transit_type',
            field=models.CharField(choices=[('return', 'return'), ('forward', 'forward')], default='forward', max_length=40),
        ),
    ]
