# Generated by Django 3.2.6 on 2021-09-17 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('payment_method', models.CharField(max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('category', models.CharField(default=None, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Order placed', max_length=70)),
                ('tracking_id', models.CharField(default=0, max_length=30)),
                ('sender_name', models.CharField(max_length=30)),
                ('sender_building', models.CharField(max_length=30)),
                ('sender_city', models.CharField(max_length=30)),
                ('sender_pin', models.CharField(max_length=10)),
                ('sender_phone', models.CharField(max_length=15)),
                ('sender_location', models.CharField(max_length=30)),
                ('sender_landmark', models.CharField(max_length=128)),
                ('receiver_name', models.CharField(max_length=30)),
                ('receiver_building', models.CharField(max_length=30)),
                ('receiver_city', models.CharField(max_length=30)),
                ('receiver_pin', models.CharField(max_length=10)),
                ('receiver_phone', models.CharField(max_length=15)),
                ('receiver_location', models.CharField(max_length=30)),
                ('receiver_landmark', models.CharField(max_length=128)),
                ('is_ordered', models.BooleanField(default=False)),
                ('payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='order.payment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
